/**
 * Project: NetControlOperations
 * File: scripts/build.mjs
 * System Version: 1.0.0 | File Version: 8 | Date: 2026-05-15
 *   v8: S5-12 — getWinlinkPracticeMessage shim added.
 *   v7: S5-11 — getNtsPracticeMessage shim added.
 *   v6: S5-10 — getIcsExport shim added.
 *   v5: S5-3 — getOthersSnapshot shim added.
 *   v4: S5-2 — getNcoLocations and recordNcoLocation shims added.
 *   v3: S5-1 — getNetTypes and saveNetTypes shims added.
 *   v2: S5-7 — reopenSession shim added; banner injects File Version into Code.gs.
 *   v1: Initial version tracking. esbuild IIFE bundle; footer shims for Apps Script.
 *
 * Build script: bundles src/server/*.ts into a single dist/Code.gs, then copies
 * src/html/index.html and appsscript.json into dist/. Run via `npm run build`.
 *
 * Teaching notes:
 *  - The `.mjs` extension tells Node "this is an ES module" so `import` works.
 *  - esbuild's `format: 'iife'` wraps the bundled code in:
 *        var __app__ = (() => { ...; return { doGet, startSession, ... }; })();
 *    so all our exported functions land on the `__app__` object.
 *  - The `footer` then emits EXPLICIT top-level function declarations that proxy
 *    into `__app__`. Why declarations rather than `this[k] = __app__[k]` property
 *    assignment: Apps Script's script editor populates its "Run" dropdown and
 *    discovers web-app / trigger entry points by STATIC parsing of the deployed
 *    code, looking for `function name() { ... }` declarations. Property assignment
 *    is invisible to that static scan even though the function would be callable
 *    at runtime — so the dropdown comes up empty and human-triggered runs (like
 *    the first-time `setupSheets()` call) have nowhere to start.
 *  - The shims forward `arguments` so they're robust to signature changes in
 *    `main.ts` (e.g. when `doGet` starts taking the event object).
 *  - We use `await import()` for esbuild and `node:fs/promises` for file ops — no
 *    callbacks; modern async/await throughout.
 */

import { build } from 'esbuild';
import { copyFile, mkdir, readFile, rm } from 'node:fs/promises';

const SRC_ENTRY = 'src/server/main.ts';
const SRC_HTML = 'src/html/index.html';
const SRC_MANIFEST = 'appsscript.json';
const DIST = 'dist';
const DIST_CODE = `${DIST}/Code.gs`;
const DIST_HTML = `${DIST}/index.html`;
const DIST_MANIFEST = `${DIST}/appsscript.json`;

/** Extract the "System Version: ... | File Version: N | Date: ..." line from main.ts. */
async function readVersionLine() {
  const src = await readFile(SRC_ENTRY, 'utf8');
  const match = src.match(/System Version:[^\n]+/);
  return match ? match[0].trim() : 'System Version: unknown';
}

async function main() {
  // Clean and recreate dist/.
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  const versionLine = await readVersionLine();
  const codeGsBanner = [
    '// Project: NetControlOperations | File: Code.gs (generated from src/server/main.ts)',
    `// ${versionLine}`,
    '// Do not edit this file directly — edit the source files and run npm run build.',
  ].join('\n');

  // Bundle TypeScript sources into one Apps Script-compatible file.
  await build({
    entryPoints: [SRC_ENTRY],
    bundle: true,
    outfile: DIST_CODE,
    format: 'iife',
    globalName: '__app__',
    banner: { js: codeGsBanner },
    footer: {
      js: [
        // Slice 1-2 functions.
        'function doGet() { return __app__.doGet.apply(this, arguments); }',
        'function startSession() { return __app__.startSession.apply(this, arguments); }',
        'function recordCheckin() { return __app__.recordCheckin.apply(this, arguments); }',
        'function endSession() { return __app__.endSession.apply(this, arguments); }',
        'function reopenSession() { return __app__.reopenSession.apply(this, arguments); }',
        'function setupSheets() { return __app__.setupSheets.apply(this, arguments); }',
        'function getRosterSnapshot() { return __app__.getRosterSnapshot.apply(this, arguments); }',
        // Slice 3 functions.
        'function resolveName() { return __app__.resolveName.apply(this, arguments); }',
        'function setManualName() { return __app__.setManualName.apply(this, arguments); }',
        'function reconcileOthersNames() { return __app__.reconcileOthersNames.apply(this, arguments); }',
        'function sundaySync() { return __app__.sundaySync.apply(this, arguments); }',
        'function installSundaySyncTrigger() { return __app__.installSundaySyncTrigger.apply(this, arguments); }',
        // Slice 4 functions.
        'function getAdminStatus() { return __app__.getAdminStatus.apply(this, arguments); }',
        'function getTemplates() { return __app__.getTemplates.apply(this, arguments); }',
        'function getRepeaterSystems() { return __app__.getRepeaterSystems.apply(this, arguments); }',
        'function saveTemplate() { return __app__.saveTemplate.apply(this, arguments); }',
        'function deleteTemplate() { return __app__.deleteTemplate.apply(this, arguments); }',
        // S5-1 functions.
        'function getNetTypes() { return __app__.getNetTypes.apply(this, arguments); }',
        'function saveNetTypes() { return __app__.saveNetTypes.apply(this, arguments); }',
        // S5-2 functions.
        'function getNcoLocations() { return __app__.getNcoLocations.apply(this, arguments); }',
        'function recordNcoLocation() { return __app__.recordNcoLocation.apply(this, arguments); }',
        // S5-3 functions.
        'function getOthersSnapshot() { return __app__.getOthersSnapshot.apply(this, arguments); }',
        // S5-10 functions.
        'function getIcsExport() { return __app__.getIcsExport.apply(this, arguments); }',
        // S5-11 functions.
        'function getNtsPracticeMessage() { return __app__.getNtsPracticeMessage.apply(this, arguments); }',
        // S5-12 functions.
        'function getWinlinkPracticeMessage() { return __app__.getWinlinkPracticeMessage.apply(this, arguments); }',
      ].join('\n'),
    },
    target: 'es2020',
    platform: 'neutral',
    charset: 'utf8',
    logLevel: 'info',
  });

  // Copy the HtmlService template and the Apps Script manifest verbatim.
  await copyFile(SRC_HTML, DIST_HTML);
  await copyFile(SRC_MANIFEST, DIST_MANIFEST);

  console.log(`\nBuild OK:\n  ${DIST_CODE}\n  ${DIST_HTML}\n  ${DIST_MANIFEST}\n`);
}

main().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
